[config]
# ...

[templates.kitty]
input_path = '/home/tpp57/.config/kitty/kitty_temp.conf'
output_path = '/home/tpp57/.config/kitty/colors.conf'

[templates.hyprland]
input_path = '/home/tpp57/.config/matugen/hyprland_color_temp.conf'
output_path = '~/.config/hypr/colors.conf'

[config.reload_apps_list]
kitty=true
hyprland=true
