preload = /home/tpp57/Downloads/4IeeGjMXE2AErgpOVeh8Gbgu.jpeg


wallpaper = DP-3,/home/tpp57/Downloads/4IeeGjMXE2AErgpOVeh8Gbgu.jpeg
wallpaper = HDMI-A-1,/home/tpp57/Downloads/4IeeGjMXE2AErgpOVeh8Gbgu.jpeg
